"use client"

import { NextUIProvider } from '@nextui-org/react'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '@/components/Provider'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dashboard-2.0',
  description: 'Generated by AMEER ',
}

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode,session?: any
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider session={session}>

      <NextUIProvider>
        {children}
  </NextUIProvider>
  </Provider>

  </body>
    </html>
  )
}
